UI作成 ユーザー情報ヒアリング画面群
AventulifeApp/nexpot-mobile-app pull request #15
Opened 2022-08-09 00:27 UTC by illbe19

## ISSUEリンク
[画面詳細設計] ユーザー情報ヒアリング画面群 #5

## 特にレビュアーに気をつけてみて欲しいところ

## 単体テスト項目

| NO | ケース | 備考 |
| --- | --- | --- |
| 1 | activeになっている/activeになっていないリストの背景色がそれぞれデザインと一致するか | - |
| 2 | 観光人数選択画面の「次へ」を押したら、興味カテゴリ選択画面に遷移するか | - |
| 3 | 観光人数選択画面に必要な項目が表示されているか（ひとり・カップル・家族・グループ） | - |
| 4 | 興味カテゴリ択画面に必要な項目が表示されているか（歴史・自然・グルメ・ショッピング・レジャー） | - |

2022-08-09 00:47 UTC, damono999 commented on lib/category_select.dart
> +  ];
モデルを参考に別ファイルで定義お願いします！
lib/constants配下に定義してあげるといいかもしれないです
ファイル名は`SightseeingSpotCategory.dart`などがいいですね 👀 

https://github.com/AventulifeApp/documents/wiki/%5BNexpot%5D-Master-Data-Modeling#-sightseeingspotcategory

2022-08-09 00:57 UTC, damono999 requested changes
@illbe19 
レビューしました！
確認お願いします！

2022-08-09 00:57 UTC, damono999 commented on lib/category_select.dart
> +                      'images/sightseeing-user-category-select/castle.png',
[must]
こちらは修正されると思いますが念の為、constantsから取得した値の設定をお願いします。

2022-08-09 00:57 UTC, damono999 commented on lib/category_select.dart
> +
[should]
lib/utilsを作成してhexColorという方で定義してあげるのがいいかと思います。

2022-08-09 00:57 UTC, damono999 commented on lib/category_select.dart
> +}
[should]
1. 三ヶ所ぐらい使用すると思うので、デザインはそのままでtitleだけ受け取れるようにお願いします。
2. lib/widgetフォルダを作成してtitle_area.dartを作成して移動してください。
3. 部品にはpadding又はmarginを持たせないようしてください。⇨部品を使用するページ側で基本的に間隔を調整します。

```suggestion
Widget TitleArea(title) {
  return Container(
    child:Text(
      title,
      style: TextStyle(
          color: HexColor('1E234D'),
          fontSize: 20,
          fontWeight: FontWeight.bold
      ),
    ),
  );
}
```

2022-08-09 00:57 UTC, damono999 commented on lib/category_select.dart
> +}
[should]
1. lib/widgetフォルダ配下して移動してください。
2. 部品にはpadding又はmarginを持たせないようしてください。

```suggestion
Widget ListArea(context, String category_name, String img_path, bool is_selected) {
  return Container(
    decoration: BoxDecoration(
        border: Border.all(color: HexColor('F2F6FC')),
        borderRadius: BorderRadius.all(
          Radius.circular(10),
        ),
        color: is_selected ? HexColor('F2F6FC') : null
    ),

    child: ListTile(
      contentPadding: EdgeInsets.only(left: 0,right: 50),
      leading: Image.asset(
        'images/sightseeing-user-category-select/Rectangle.png',
        fit: BoxFit.contain,
        color: is_selected ? null : HexColor('F2F6FC'),
      ),
      trailing: Image.asset(
        img_path,
        fit: BoxFit.fitWidth,
        color: is_selected ? HexColor('0065CC') : HexColor('1E234D'),
      ),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(10),
      ),
      minLeadingWidth: 30,
      title: Text(
        category_name,
        textAlign: TextAlign.left,
        style: TextStyle(
            color: HexColor('1E234D'),
            fontWeight: FontWeight.bold
        ),
      ),
      onTap: () {
        showDialog(
            context: context,
            builder: (context) => AlertDialog(
              content: Text('Tap $category_name'),
            )
        );
        },
    ),
  );
}
```

2022-08-09 00:57 UTC, damono999 commented on lib/category_select.dart
> +}
[should]
1. lib/widgetフォルダ配下して移動してください。

2022-08-09 00:57 UTC, damono999 commented on lib/sightseeing_user_type_select.dart
> +  ];
[should]
lib/constantsフォルダ配下して移動してください。

2022-08-11 05:35 UTC, illbe19 commented on lib/category_select.dart
> +  ];
それぞれ、別ファイルで管理するように修正いたしました。

2022-08-11 05:37 UTC, shunnagahara commented on lib/category_select.dart
> +  ];
@damono999 @illbe19 

```dart
final List<String> categoryList = <String> [
    '歴史',
    '自然',
    'グルメ',
    'ショッピング',
    'レジャー'
  ];
```

ここに関しては、`lib/constants`配下に定義で良いと思います。

あと一点、すみません。ファイル名ですが調べましたがflutterはファイル名は基本的にはスネークケースが正しいみたいです、、

[これ](https://de-milestones.com/dart_naming_convention/)とか[これ](https://github.com/hukusuke1007/flutter_app_template/tree/main/lib/presentation)が参考になります。

（前回参画したPJで色々議論しましたが、ファイル名では無かったです、、うる覚えですみません、）

なので`sightseeing_spot-category.dart `が正しいかなと！

2022-08-11 05:40 UTC, shunnagahara commented on lib/category_select.dart
> +
@damono999 @illbe19 

> lib/utilsを作成して

ファイルの指定場所、問題ありません！

2022-08-11 05:43 UTC, shunnagahara commented on lib/category_select.dart
> +}
@illbe19 @damono999 

指摘内容に問題ありません、`lib/widget`配下に部品作成おねがいします！

（菅さんのフロントエンド技術が活きてる指摘ですね、、ここらへん私知見が疎いので助かります。）

2022-08-11 05:44 UTC, shunnagahara commented on lib/category_select.dart
> +}
@illbe19 @damono999 

認識の齟齬ありません！

2022-08-11 05:45 UTC, shunnagahara commented on lib/category_select.dart
> +}
@illbe19 @damono999

認識の齟齬ないですー

2022-08-11 05:45 UTC, shunnagahara commented on lib/sightseeing_user_type_select.dart
> +  ];
@illbe19 @damono999

認識の齟齬ないですー

2022-08-11 08:26 UTC, illbe19 commented on lib/category_select.dart
> +  ];
ご指摘いただいたとおり、
それぞれ定義して、ファイル名も修正いたしました。

2022-08-11 08:27 UTC, illbe19 commented on lib/category_select.dart
> +                      'images/sightseeing-user-category-select/castle.png',
constantsから取得した値を設定いたしました。

2022-08-11 08:28 UTC, illbe19 commented on lib/category_select.dart
> +
lib/utilsにhex_colorというファイルを作成して、読み込むようにいたしました。

2022-08-11 08:29 UTC, illbe19 commented on lib/category_select.dart
> +}
lib/widgetにファイルを作成して、そこから読み込むように修正いたしました。

2022-08-11 08:33 UTC, illbe19 commented on lib/sightseeing_user_type_select.dart
> +  ];
ご指摘いただいたとおり、lib/constantsに定義するようにいたしました。

2022-08-11 08:33 UTC, illbe19 commented
> @illbe19 レビューしました！ 確認お願いします！

@damono999 
レビューいただきました点修正いたしましたので、再度ご確認のほどよろしくおねがいします。

2022-08-11 23:56 UTC, damono999 commented
@illbe19 
LGTM 💯

2022-08-12 13:02 UTC, merged

2022-08-12 23:30 UTC, shunnagahara commented on lib/category_select.dart
> +  ];
確認しました！

クローズします！

2022-08-12 23:32 UTC, shunnagahara commented on lib/category_select.dart
> +                      'images/sightseeing-user-category-select/castle.png',
constantsから取得してることを確認しました。

クローズします！

2022-08-12 23:33 UTC, shunnagahara commented on lib/category_select.dart
> +
> lib/utilsにhex_colorというファイルを作成して、読み込むようにいたしました。

確認しました！

クローズします！

2022-08-12 23:35 UTC, shunnagahara commented on lib/category_select.dart
> +}
確認しました！

対応ありがとうございます！

2022-08-12 23:36 UTC, shunnagahara commented on lib/category_select.dart
> +}
@illbe19 

> ListViewの間隔を開けたく、Containerにmarginを設定しないと開けられなかったため、marginのみ残しております。。

一旦、大丈夫です！

今後、KPTやる時に話題として出してもらえれば幸いです！

2022-08-12 23:36 UTC, shunnagahara commented on lib/category_select.dart
> +}
確認しました

クローズします！

2022-08-12 23:37 UTC, shunnagahara commented on lib/sightseeing_user_type_select.dart
> +  ];
確認しました！

クローズしました！